# build server
# 
# This compose file will bring up all three containers required to run this build server.
# NOTE: this docker-compose file requires a .env file or an environment variable that
# specifies where the code repo is located on the host machine.
#
# HOST_CODE_PATH=/path/to/code/repository
# 
# Jason Andersen
# 2016.07.26

version: '2'
services:
  jenkins:
    image: build-jenkins
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins/.jenkins_home/:/var/jenkins_home"
      - "./.m2:/var/jenkins_home/.m2" 
      - "$HOST_CODE_PATH:/opt/code"
    env_file: ./.env

  sonarqube:    
    image: build-sonar
    ports:
      - "9000:9000"
    volumes:
      - "./sonarqube/.sonarqube_home/:/opt/sonarqube"
      - "$HOST_CODE_PATH:/opt/code"
    env_file: ./.env

  sonardb:
    image: build-mysql
    ports: 
      - "3306:3306"
    volumes:
      - "./mysql/.data/:/var/lib/mysql"
    env_file: ./.env
