version: '2'
services:
  sonardb:
    image: build-sonardb
    volumes:
      - "./mysql/.data/:/var/lib/mysql"
    ports:
      - "3306:3306"

  jenkins:
    image: build-jenkins
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins/.jenkins_home/:/var/jenkins_home"
      - "/Users/jason/dev/workspace:/opt/code"

  sonarqube:
    depends_on:
      - sonardb
    image: build-sonar
    ports:
      - "9000:9000"
    volumes:
      - "./sonarqube/.sonarqube_home/:/opt/sonarqube"
      - "/Users/jason/dev/workspace:/opt/code"