version: '2'
services:
  jenkins:
    image: build-jenkins
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins/.jenkins_home/:/var/jenkins_home"
      - "/Users/jason/dev/workspace:/opt/code"