# build server
# 
# This compose file will bring up all three containers required to run this build server.
# 
# NOTE: this file has an external dependency on environment variables described in the .env
# file in this same directory.
# 
# Jason Andersen
# 2016.07.26

version: '2'
services:
  jenkins:
    image: build-jenkins
    depends_on:
      - sonarqube
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins/.jenkins_home/:/var/jenkins_home"
      - "./.m2:/var/jenkins_home/.m2" 
      - "$HOST_CODE_PATH:/opt/code"
    env_file: ./.env

  sonarqube:    
    image: build-sonar
    depends_on:
      - sonardb
    ports:
      - "9000:9000"
    volumes:
      - "./sonarqube/.sonarqube_home/:/opt/sonarqube"
      - "$HOST_CODE_PATH:/opt/code"
    environment: 
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonardb:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    env_file: ./.env

  sonardb:
    image: build-sonardb
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/.data/:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=mmouse
    env_file: ./.env
