# build server
# 
# This compose file will bring up all three containers required to run this build server.
# 
# NOTE: this file has an external dependency on environment variables described in the .env
# file in this same directory.
# 
# Jason Andersen
# 2016.07.26

version: "3.1"
secrets:
  mysql-root-pwd:
    file: ./secrets/mysql-root-pwd
services:
  # Jenkins CI server
  jenkins:
    image: pipeline/jenkins
    build: ./jenkins
    depends_on:
      - sonarqube
    ports:
      - "8080:8080"
    volumes:
      - "$HOST_JENKINS_HOME:/var/jenkins_home"
      - "$HOST_CODE_PATH:/opt/code"
    env_file: ./.env
  # SonarQube static analysis engine
  sonarqube:    
    image: pipeline/sonarqube
    build: ./sonarqube
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    volumes:
      - "$HOST_CODE_PATH:/opt/code"
      - "$HOST_SONAR_DATA:/opt/sonarqube/data"
      - "$HOST_SONAR_CONF:/opt/sonarqube/conf"
      - "$HOST_SONAR_EXTENSIONS:/opt/sonarqube/extensions"
      - "$HOST_SONAR_PLUGINS=/opt/sonarqube/lib/bundled-plugins"
    environment: 
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube-db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    env_file: ./.env
  # MySQL database used by SonarQube to store code metrics
  sonarqube-db:
    image: pipeline/sonarqube-db
    build: ./mysql
    volumes:
      - "$HOST_MYSQL_DATA:/var/lib/mysql"
    secrets:
      - mysql-root-pwd
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-pwd
  # Docker registry to house images
  registry:
    restart: always
    image: pipeline/registry
    build: ./registry
    volumes:
      - "$HOST_DOCKER_REGISTRY:/var/lib/registry"
    ports:
      - "5000:5000"
  # Nexus artifact repository to store and serve code binaries
  nexus:
    image: pipeline/nexus
    build: nexus
    volumes:
      - "$HOST_NEXUS_DATA:/sonatype-work"
    ports:
      - "8081:8081"

