# build server
# 
# This compose file will bring up all three containers required to run this build server.
# 
# NOTE: this file has an external dependency on environment variables described in the .env
# file in this same directory.
# 
# Jason Andersen
# 2016.07.26

version: '2'
services:
  jenkins:
    image: pipeline/jenkins
    depends_on:
      - sonarqube
    ports:
      - "8080:8080"
    volumes:
      - "$HOST_JENKINS_HOME:/var/jenkins_home"
      - "$HOST_CODE_PATH:/opt/code"
    env_file: ./.env

  sonarqube:    
    image: pipeline/sonarqube
    depends_on:
      - sonardb
    ports:
      - "9000:9000"
    volumes:
      - "$HOST_CODE_PATH:/opt/code"
      - "$HOST_SONAR_DATA:/opt/sonarqube/data"
      - "$HOST_SONAR_CONF:/opt/sonarqube/conf"
      - "$HOST_SONAR_EXTENSIONS:/opt/sonarqube/extensions"
      - "$HOST_SONAR_PLUGINS=/opt/sonarqube/lib/bundled-plugins"
    environment: 
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube-db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    env_file: ./.env

  sonardb:
    image: pipeline/sonarqube-db
    volumes:
      - "$HOST_MYSQL_DATA:/var/lib/mysql"
    env_file: ./.env

  registry:
    restart: always
    image: pipeline/registry
    volumes:
      - "$HOST_DOCKER_REGISTRY:/var/lib/registry"
    ports:
      - "5000:5000"

  nexus:
    image: pipeline/nexus
    volumes:
      - "$HOST_NEXUS_DATA:/sonatype-work"
    ports:
      - "8081:8081"
