CREATE DATABASE IF NOT EXISTS sonar;
CREATE USER IF NOT EXISTS '$SONAR_JDBC_USERNAME'@'localhost' IDENTIFIED BY '$SONAR_JDBC_PASSWORD';
GRANT ALL ON 'sonar'.* to '$SONAR_JDBC_USERNAME'@'localhost' IDENTIFIED BY '$SONAR_JDBC_PASSWORD'; 
